version: '3.4'

services:
  sl7:
    image: sl7:latest
    container_name: sl7
    build: ./sl7
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
      - WORK=/work
      - DATA=/work/data
    volumes:
      - type:   bind
        source: ${WORK}/hep
        target: /work
      - type:   bind
        source: ${WORK}/hep/sl7/home
        target: /home/james
      - type:   bind
        source: /cvmfs
        target: /cvmfs
      - type:   bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    network_mode:    host
    user: 1000:1000
    ports:
      - "8888:8888"

